- hosts: masters
  become: yes
  tasks:
    - name: initialize the cluster
      
      shell: kubeadm init --apiserver-advertise-address=10.210.12.231 --pod-network-cidr=192.168.0.0/16  --ignore-preflight-errors=all

      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create kube file
      shell: |
               mkdir -p $HOME/.kube
               sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
               sudo chown $(id -u):$(id -g) $HOME/.kube/config
           

    # - name: create .kube directory
    #   become: yes
    #   become_user: "{{ userName }}"
    #   file:
    #     path: $HOME/.kube
    #     state: directory
    #     mode: 0755

    # - name: copies admin.conf to user's kube config
    #   copy:
    #     src: /etc/kubernetes/admin.conf
    #     dest: /home/{{ userName }}/.kube/config
    #     remote_src: yes
    #     owner: "{{ userName }}"

    # - name: change ownership
    #   become: yes
    #   become_user: "{{ userName }}"
    #   shell: chown $(id -u):$(id -g) $HOME/.kube/config

    # - name: install wave network
    #   become: yes
    #   become_user: "{{ userName }}"
    #   # shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
    #   shell: kubectl apply -f "https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml"
    #   args:
    #     chdir: $HOME
        
    # - name: Get the token for joining the worker nodes
    #   become: yes
    #   become_user: "{{ userName }}"
    #   shell: kubeadm token create  --print-join-command
    #   register: kubernetes_join_command

    # - debug:
    #     msg: "{{ kubernetes_join_command.stdout }}"
    #     # var: kubernetes_join_command.stdout_lines

    # - name: Copy join command to local file.
    #   become: yes
    #   local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
    #   # copy: content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
